version: '2.3'

services:
  madcat:
      container_name: madcat
      restart: always
      network_mode: "host"
      cap_add:
        - NET_ADMIN
      tmpfs:
        - /tmp
      build: .
      image: "madcat:2022"
      volumes:
        - ./data/:/data
        - ./data/ipm/:/data/ipm
        - ./data/upm/:/data/upm
        - ./data/tpm/:/data/tpm
        - ./etc/madcat/config.lua:/etc/madcat/config.lua